apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: gojirastats
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "gojirastats"
        spec:
          containers:
          - env:
            - name: QUERIES_FILE
              value: /etc/jirastats/queries.json
            - name: INFLUX_URL
              value: https://myinfludb.example.com:8086
            - name: INFLUX_USER
              value: gojirastats
            - name: INFLUX_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: INFLUX_PASSWORD
                  name: gojiratstats
            - name: INFLUX_DB
              value: jirastats
            - name: JIRA_URL
              value: https://myjira.example.com
            - name: JIRA_USER
              value: myjirauser
            - name: JIRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: JIRA_PASSWORD
                  name: gojiratstats
            image: vshn/gojirastats
            imagePullPolicy: Always
            name: gojirastats
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/jirastats
              name: config-volume
          dnsPolicy: ClusterFirst
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: gojiratstats-queries
            name: config-volume
          restartPolicy: OnFailure
